"""Default catalog seed data extracted from the original Vinyl Siding Estimator HTML."""

DEFAULT_SECTIONS = [
    {"title": "Install Vinyl Siding", "ascend": False, "items": [
        {"name": "Conquest", "unit": "SQ", "mat": 92.19, "lab": 125},
        {"name": "Vertical board and batten", "unit": "SQ", "mat": 136.56, "lab": 125},
        {"name": "Odyssey (standard colors)", "unit": "SQ", "mat": 116.22, "lab": 125},
        {"name": "Charter Oak (standard colors)", "unit": "SQ", "mat": 125.46, "lab": 125},
        {"name": "Ascend Composite Lap Siding", "unit": "SQ", "mat": 332.60, "lab": 150},
        {"name": "Ascend Composite B&B (add 30% Waste)", "unit": "SQ", "mat": 408.66, "lab": 150},
        {"name": "Architectural color upcharge Vinyl", "unit": "SQ", "mat": 0, "lab": 16},
        {"name": "Shakes and Scallops", "unit": "SQ", "mat": 419.00, "lab": 125},
    ]},
    {"title": "Ascend Accessories", "ascend": True, "items": [
        {"name": 'Ascend 3.5" Outside Corner — Matte', "unit": "PCS", "mat": 40.42, "lab": 0},
        {"name": 'Ascend 5.5" Outside Corner — Matte', "unit": "PCS", "mat": 59.36, "lab": 0},
        {"name": "Inside Corners", "unit": "PCS", "mat": 11.83, "lab": 0},
        {"name": "Ascend 5.5\" H-Channel (16' length)", "unit": "PCS", "mat": 71.66, "lab": 0},
        {"name": "Ascend J-Channel (2 per SQ of siding)", "unit": "LF", "mat": 10.40, "lab": 0},
    ]},
    {"title": "Siding Accessories", "ascend": False, "items": [
        {"name": ".019 Coil (1 per 5 SQ siding)", "unit": "ROLL", "mat": 133.23, "lab": 0},
        {"name": "Outside corners", "unit": "PCS", "mat": 23.66, "lab": 0},
        {"name": "Inside Corners", "unit": "PCS", "mat": 11.83, "lab": 0},
        {"name": "J-Channel (2 per SQ of siding)", "unit": "PCS", "mat": 5.20, "lab": 0},
        {"name": "Finish Trim", "unit": "LF", "mat": 0.54, "lab": 0},
        {"name": "Starter", "unit": "LF", "mat": 0.45, "lab": 0},
        {"name": "House Wrap", "unit": "SQ", "mat": 11.55, "lab": 2.50},
        {"name": "RainDrop", "unit": "SQ", "mat": 30.73, "lab": 2.50},
        {"name": '3/8" Fan Fold', "unit": "SQ", "mat": 11.06, "lab": 5},
        {"name": '2" Nails 30 lbs (1 per 15 SQ)', "unit": "JOB", "mat": 81.63, "lab": 0},
        {"name": "Caulking (per color)", "unit": "Each", "mat": 8.23, "lab": 0},
        {"name": "J-blocks, Dryer vents", "unit": "Each", "mat": 13.49, "lab": 10},
        {"name": "Shutters (louvered, raised panel) standard sizes", "unit": "PR", "mat": 114.22, "lab": 20},
        {"name": "Gable vents (round, octagon)", "unit": "Each", "mat": 92.29, "lab": 10},
        {"name": "Trim Nails", "unit": "Box", "mat": 9.00, "lab": 0},
    ]},
    {"title": "Tear-Off / Clean Up", "ascend": False, "items": [
        {"name": "Tear-Off", "unit": "SQ", "mat": 0, "lab": 10},
        {"name": "Wood shake tear-off (requires a dumpster)", "unit": "SQ", "mat": 0, "lab": 80.25},
        {"name": "Clean up / haul away job debris", "unit": "JOB", "mat": 0, "lab": 150},
        {"name": "Dumpster", "unit": "Each", "mat": 0, "lab": 550},
    ]},
    {"title": "Vinyl Soffit with Siding", "ascend": False, "items": [
        {"name": 'Soffit & fascia up to 13" wide — Charter Oak', "unit": "LF", "mat": 1.82, "lab": 2.75},
        {"name": 'Soffit & fascia up to 13" wide — Greenbriar', "unit": "LF", "mat": 1.62, "lab": 2.75},
        {"name": 'Soffit & fascia up to 13" — T2', "unit": "LF", "mat": 1.38, "lab": 2.75},
        {"name": 'Soffit & fascia 13"–30" wide — Charter Oak', "unit": "LF", "mat": 3.64, "lab": 3.50},
        {"name": 'Soffit & fascia 13"–30" wide — Greenbriar', "unit": "LF", "mat": 3.24, "lab": 3.50},
        {"name": 'Soffit & fascia 13"–30" — T2', "unit": "LF", "mat": 2.76, "lab": 3.50},
        {"name": 'Fascia/rake or frieze up to 8" coverage', "unit": "LF", "mat": 2.94, "lab": 1.25},
        {"name": "Cap porch band", "unit": "LF", "mat": 2.94, "lab": 1.25},
    ]},
    {"title": "Porch Ceiling", "ascend": False, "items": [
        {"name": "With or without siding — Charter Oak", "unit": "SQ FT", "mat": 1.17, "lab": 1.25},
        {"name": "Wrap porch beam", "unit": "LF", "mat": 5.88, "lab": 3},
    ]},
    {"title": "Seamless Gutter", "ascend": False, "items": [
        {"name": 'Gutter 6"', "unit": "LF", "mat": 3.25, "lab": 1.25},
        {"name": 'Downspout 6"', "unit": "LF", "mat": 2.80, "lab": 1},
        {"name": "Elbow", "unit": "Each", "mat": 2.69, "lab": 1},
        {"name": "Mitre", "unit": "Each", "mat": 13.75, "lab": 12},
        {"name": "Gutter Guard (USA Shurflo)", "unit": "LF", "mat": 2.25, "lab": 0.50},
    ]},
    {"title": "Misc. Labor Only", "ascend": False, "items": [
        {"name": "R&R gutter", "unit": "LF", "mat": 0, "lab": 1},
        {"name": "R&R downspout", "unit": "LF", "mat": 0, "lab": 0.75},
    ]},
    {"title": "Misc. Labor & Material", "ascend": False, "items": [
        {"name": "Cap window", "unit": "Each", "mat": 0, "lab": 20},
        {"name": "Cap windows with wide crown", "unit": "Each", "mat": 65, "lab": 30},
        {"name": "Capping general", "unit": "LF", "mat": 0, "lab": 1},
        {"name": "Cap window headers only", "unit": "Each", "mat": 0, "lab": 8},
        {"name": "Cap entry door", "unit": "Each", "mat": 0, "lab": 25},
        {"name": "Cap patio door", "unit": "Each", "mat": 0, "lab": 30},
        {"name": "Cap single garage door", "unit": "Each", "mat": 0, "lab": 40},
        {"name": "Build out for windows w/ furring (includes capping)", "unit": "Each", "mat": 0, "lab": 50},
        {"name": "R&R Gable louvers", "unit": "Each", "mat": 0, "lab": 10},
        {"name": "Fascia Return", "unit": "Each", "mat": 0, "lab": 8},
        {"name": "Bird box", "unit": "Each", "mat": 0, "lab": 10},
        {"name": "Flashing", "unit": "LF", "mat": 0, "lab": 1},
    ]},
    {"title": "Misc.", "ascend": False, "items": [
        {"name": "Cap tops of bird boxes", "unit": "Each", "mat": 60, "lab": 1},
        {"name": "Dormer upcharge", "unit": "Each", "mat": 0, "lab": 100},
        {"name": "R&R Utilities", "unit": "Each", "mat": 0, "lab": 1},
        {"name": "Cut out 4x4 section of wall and insulate", "unit": "Each", "mat": 100, "lab": 50},
    ]},
]
