// Color palettes per product line. Used by the dropdowns on the estimate
// page (Job Info → Material Colors / Window Colors blocks). One palette
// per field; the contractor must pick a value from the list — no free-text.
//
// Add or edit a palette here and the dropdown updates automatically. Order
// matters: items are rendered in this order, so put the most common picks
// at the top.

export const VINYL_SIDING_COLORS = [
  "Glacier White",
  "Juniper Ridge",
  "Platinum Gray",
  "Monterey Sand",
  "Tuscan Clay",
  "Antique Parchment",
  "Adobe Cream",
  "Natural Linen",
  "Cape Cod Gray",
  "Maple",
  "Vintage Wicker",
  "Mystic Blue",
  "Coastal Sage",
  "Fired Brick",
  "Harbor Blue",
  "Deep Espresso",
  "Riviera Dusk",
  "Canyon Drift",
  "Midnight Blue",
  "Rustic Timber",
  "Storm",
  "Mountain Fern",
  "Deep Moss",
  "Sterling Gray",
  "Ageless Slate",
  "Flagship Brown",
  "Laguna Blue",
  "Charcoal Smoke",
  "Cast Iron",
];

export const ASCEND_COLORS = [
  "Glacier White",
  "Almond",
  "Monterey Sand",
  "Pebble",
  "Canyon Drift",
  "Flagship Brown",
  "Rustic Timber",
  "Dover Gray",
  "Cape Cod Gray",
  "Sterling Gray",
  "Storm",
  "Ageless Slate",
  "Charcoal Smoke",
  "Cast Iron",
  "Laguna Blue",
  "Harbor Blue",
  "Midnight Blue",
  "Riviera Dusk",
  "Mountain Fern",
  "Deep Moss",
  "Fired Brick",
];

// Soffit / Fascia palette. Same shape as the vinyl siding palette but
// includes a few extra colors that ship on aluminum soffit/fascia stock
// only (Musket Brown, Black) and omits a few darker vinyl-only colors.
export const SOFFIT_COLORS = [
  "Glacier White",
  "Antique Parchment",
  "Natural Linen",
  "Platinum Gray",
  "Cape Cod Gray",
  "Mystic Blue",
  "Coastal Sage",
  "Juniper Ridge",
  "Adobe Cream",
  "Maple",
  "Monterey Sand",
  "Vintage Wicker",
  "Tuscan Clay",
  "Fired Brick",
  "Canyon Drift",
  "Flagship Brown",
  "Deep Espresso",
  "Musket Brown",
  "Rustic Timber",
  "Mountain Fern",
  "Deep Moss",
  "Harbor Blue",
  "Midnight Blue",
  "Laguna Blue",
  "Riviera Dusk",
  "Storm",
  "Sterling Gray",
  "Ageless Slate",
  "Charcoal Smoke",
  "Cast Iron",
  "Black",
];
